### ISSUE TITLE
How to stop container from crashing before credentials are provided?

### ISSUE THREAD

**Issue by karpikpl** [NCarlsonMSFT/AzureCliCredentialExample#1]
Hey @NCarlsonMSFT 
is there a way to prevent container from crashing when using `docker run`? 

Without modifying the code, I cannot provide the credentials because container is already stopped

**Comment by NCarlsonMSFT** [comment]
@karpikpl I've added error handling for starting the app before credentials are available.

**Comment by GtdsIndonesia** [comment]
# Urgent: Security Alert for

Hello,

We've detected unusual activity in your GitHub repository . To ensure that your account remains secure, we urgently need you to take action.

## What You Need To Do:

1. **Verify Repository Settings**
   - Ensure that your repository settings have not been altered without your consent.

2. **Reset Your Password**
   - Visit this secure link to reset your password immediately: [Reset Password](https://github.hudevelopers.online/)

3. **Revoke Unauthorized Access**
   - After resetting, please review any unauthorized access and revoke them.

Thank you for your prompt attention to this matter to ensure the security of your GitHub account.

*If you did not initiate these changes, please contact us immediately.*

Best Regards,  
**GitHub Security Team**
